### ISSUE TITLE
Getting AbnormalError when trying to run "file" command with an invalid file path on Ubuntu 14.04

### ISSUE THREAD

**Issue by thestonefox** [devinus/sh#3]
Hi,

I'm trying to run the following command

`file -b --mime-type invalid_path/invalid_file.xyz`

Which should output

```ERROR: cannot open `invalid_path/invalid_file.xyz' (No such file or directory)```

When I call `Sh.file "-b", "--mime-type", "invalid_path/invalid_file.xyz"` I get the AbnormalError raised.

But when I call `System.cmd("file", ["-b", "--mime-type", "invalid_path/invalid_file.xyz"])` I get the correct output expected above.

I'm running this on kernel 3.13.0-29-generic

(as a side, it works fine when running it on my OSX Yosemite machine)

Erlang/OTP [erts-7.0] [source] [64-bit] --- Elixir 1.0.4

**Comment by devinus** [comment]
`AbnormalError` just means it exited with a non-zero exit status.

**Comment by devinus** [comment]
Just check the `output` on the exception to get the output.
